config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :contact_requests, only: [:index, :new, :create, :show]
  resource :complaint, only: [:new, :create]

  root 'contact_requests#new'
  get 'admin', to: 'contact_requests#index'

  mount ContactRequestApi::V1 => '/'
  mount GrapeSwaggerRails::Engine, at: "/documentation"
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_access_token
  before_create :set_expiration
  belongs_to :user

  def expired?
    DateTime.now >= self.expires_at
  end

  private
  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end

  def set_expiration
    # Change the expiration range if we want
    self.expires_at = DateTime.now + 9999
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complaint_form.rb
class ComplaintForm
  include ActiveModel::Model

  attr_accessor :name, :product, :email, :body

  validates :name, :body, :product, presence: true
  validates :email, presence: true, format: { with: Devise.email_regexp }

  def save
    if valid?
      ComplaintMailer.send_message(form_info).deliver_later
      true
    else
      false
    end
  end

  private

  def form_info
    { name: name, product: product, email: email, body: body }
  end
end

app/models/contact_request.rb
class ContactRequest < ApplicationRecord
  scope :by_subject, ->(direction) { order subject: direction }
  scope :by_date, ->(direction) { order created_at: direction }
  scope :by_author, ->(direction) { order name: direction}

  validates :name, :email, :subject, :comment, presence: true
  validates_format_of :email,
                      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_format_of :name,
                      with: /\A(?=.* )[^0-9`!@#\\\$%\^&*\;+_=]{4,}\z/i

  has_attached_file :file
  validates_attachment :file,
                       content_type:
                        {
                          content_type: [
                            'image/jpeg',
                            'image/jpg',
                            'image/png',
                            'application/pdf',
                            'application/msword',
                            'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
                          ]
                        }
  after_save :send_email

  belongs_to :user, optional: true

  def user
    super || NullObjects::NullUser.new
  end

  private

  def send_email
    RequestMailSender.perform_later(id)
  end
end

app/models/null_objects/null_user.rb
module NullObjects
  class NullUser
    def admin
      false
    end

    def email
      'N/A'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contact_requests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  def new
    @complaint_form = ComplaintForm.new
  end

  def create
    @complaint_form = ComplaintForm.new(complaint_form_params)

    if @complaint_form.save
      redirect_to new_complaint_path
      flash[:success] =  t('.complaint_info')
    else
      render action: :new
    end
  end

    private

    def complaint_form_params
      params.require(:complaint_form).permit(:name, :product, :email, :body)
    end
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  before_action :set_contact_request, only: [:show, :update, :destroy]
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    @contact_requests = OrderedContactRequestsQuery.new(sort_query_params).all.page(params[:page]).per(6)
    authorize @contact_requests
  end

  def show
    @user = @contact_request.user
  end

  def new
    @contact_request = ContactRequest.new
    authorize @contact_request
  end

  def edit
  end

  def create
    @contact_request = ContactRequest.new(contact_params)
    @contact_request.user = current_user if current_user
    authorize @contact_request
    if @contact_request.save
      redirect_to root_path
      flash[:success] = 'Contact request was successfully created.'
    else
      render 'new'
    end
  end

  def destroy
    @contact_request.destroy
    redirect_to admin_path
    flash[:success] = 'Contact request was successfully destroyed.'
  end

  private

  def contact_params
    params.require(:contact_request).permit(
      :name,
      :email,
      :subject,
      :comment,
      :file,
      :user_id
    )
  end

  def set_contact_request
    @contact_request = ContactRequest.find(params[:id])
    authorize @contact_request
  end

  def user_not_authorized
    flash[:warning] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def sort_query_params
    params.slice(:sort_by, :direction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def view_object(name, args = {})
    class_name = name.to_s.titleize.split(' ').join('')
    class_name.constantize.new(args)
  end
end

app/views/complaints/new.haml
- flash.each do |key, value|
  .alert{ class: "alert-#{key}" }
    %button.close{ data: { dismiss: "alert" } } x
    %strong
      = value
.col-xs-12
  .panel.panel-primary
    .panel-heading
      = t('.please_fill')
    .panel-body
      .container
        .form-group.form-horizontal
          = simple_form_for @complaint_form, url: complaint_path do |f|
            = f.input :name, label: t('.name'), as: :string, required: true
            = f.input :product, collection: [ "P1, P2, P2S", "Helvetica, Boombox, cocacola, zippo"],
                                            label: t('.product'), include_blank: false
            = f.input :email, label: t('.email'), as: :email, required: true
            = f.input :body, label: t('.complaint'), as: :text, required: true
            = f.submit t('.submit')

app/views/complaints/show.haml
- flash.each do |key, value|
  .alert{ :class => "alert-#{key}" }
    %button.close{ :data => { :dismiss => "alert" } } x
    %strong
      = value
.col-xs-12
  .panel.panel-primary
    .panel-heading Complaint Form, please fill the form:
    .panel-body
      .container
        .form-group.form-horizontal
          = simple_form_for @complaint_form, url: complaint_path do |f|
            = f.input :name, label: t('.name'), as: :string, required: true
            = f.input :product, collection: [ "P1, P2, P2S", "Helvetica, Boombox, cocacola, zippo"],
                                            label: t('.product'), required: true
            = f.input :email, label: t('.email'), as: :email, required: true
            = f.input :body, label: t('.complaint'), as: :text, required: true
            = f.submit I18n.t('.submit')

app/views/contact_requests/index.haml
- flash.each do |key, value|
  .alert{ class: "alert-#{key}" }
    %button.close{ data: { dismiss: "alert" } } x
    %strong
      = value
= link_to('By author - ascending', contact_requests_path(sort_by: :by_author, direction: :asc))
= link_to('By author - descending', contact_requests_path(sort_by: :by_author, direction: :desc))
.col-xs-12
  .panel.panel-primary
    .panel-heading All contact requests:
    .panel-body
    .container
      %table.table.table-hover
        %thead
          %tr
            %th
              = I18n.t('.user_login')
            %th
              = I18n.t('.user_admin')
            %th
              = I18n.t('.name')
            %th
              = I18n.t('.email')
            %th
              = I18n.t('.subject_line')
            %th
              = I18n.t('.more_details')

        %tbody
          - @contact_requests.each do |contact_request|
            %tr
              - user = contact_request.user
              %td= user.email
              %td= user.admin
              %td= contact_request.name
              %td= contact_request.email
              %td= contact_request.subject
              %td= link_to "Details", contact_request_path(contact_request.id)
    = paginate @contact_requests
    = page_entries_info @contact_requests
- if user_signed_in?
  %p
    = link_to('Logout', destroy_user_session_path, method: :delete)
- else
  %p
    = link_to('Login', new_user_session_path)

app/views/contact_requests/new.haml
- flash.each do |key, value|
  .alert{ class: "alert-#{key}" }
    %button.close{ data: { dismiss: "alert" } } x
    %strong
      = value
= @current_user.present? ? @current_user.email : "guest"
.col-xs-12
  .panel.panel-primary
    .panel-heading Please fill in contact form:
    .panel-body
      .container
        .form-group.form-horizontal
          = simple_form_for @contact_request, html: { multipart: true }, url: contact_requests_path do |f|
            = f.input :name, label: t('.name'), as: :string, required: true
            = view_object(:contact_request_errors, form: @contact_request, attribute: :name).html
            = f.input :email, label: t('.email'), as: :string, required: true
            = view_object(:contact_request_errors, form: @contact_request, attribute: :email).html
            = f.input :subject,label: t('.subject'), as: :string, required: true
            = view_object(:contact_request_errors, form: @contact_request, attribute: :subject).html
            = f.input :comment,label: t('.comment'), as: :string, required: true
            = view_object(:contact_request_errors, form: @contact_request, attribute: :comment).html
            = f.input :file, label: t('.attachment'), as: :file
            = view_object(:contact_request_errors, form: @contact_request, attribute: :file).html

            = f.submit I18n.t('.submit')
  %p
    = link_to(t('.complaint_link'), new_complaint_path)
  - if user_signed_in?
    %p
      = link_to(I18n.t('.logout'), destroy_user_session_path, :method => :delete)
    %p
    - if current_user.admin?
      = link_to(I18n.t('.admin_panel'), admin_path)
  - else
    %p
      = link_to(I18n.t('.login'), new_user_session_path)

app/views/contact_requests/show.haml
- flash.each do |key, value|
  .alert{ class:  "alert-#{key}" }
    %button.close{ data: { dismiss: "alert" } } x
    %strong
      = value
.col-xs-12
  .panel.panel-primary
    .panel-heading All contact requests:
    .panel-body
    .container
      %table.table.table-hover
        %thead
          %tr
            %th
              = I18n.t('.user_login')
            %th
              = I18n.t('.user_admin')
            %th
              = I18n.t('.name')
            %th
              = I18n.t('.email')
            %th
              = I18n.t('.subject_line')
            %th
              = I18n.t('.comment')
            %th
              = I18n.t('.file_preview')
            %th Created_at:
        %tbody
          %tr
            %td= @user.email
            %td= @user.admin
            %td= @contact_request.name
            %td= @contact_request.email
            %td= @contact_request.subject
            %td= @contact_request.comment
            %td
              - if @contact_request.file.url.include? 'missing.png'
                = 'n/a'
              - else
                = link_to (image_tag @contact_request.file.url), @contact_request.file.url
            %td= @contact_request.created_at
    = link_to('Back to index', contact_requests_path)

- if user_signed_in?
  %p
    = link_to('Logout', destroy_user_session_path, method: :delete)
- else
  %p
    = link_to('Login', new_user_session_path)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompanySite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>